---
title: "R_01_Testing_Hierarchichal"
author: "Oren"
date: "9/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(fable)
library(tsibble)
library(dplyr)
library(tidyverse)
library(reshape2)
library(ggplot2)
library(plotly)
library(feasts)
library(imputeTS)
library(tidymodels)
library(skimr)
library(zoo)
```


```{r}
zri_df_og <-read_csv("../../data/HIER_zri_multifamily_v2.csv")
```

```{r}
zri_df <- select(zri_df_og, -c('SizeRank', 'Metro')) 

zri_df <- drop_na(zri_df)

zri_df_melted <- melt(zri_df, id.vars = c('zip', 'City', 'State',  'CountyName'))
zri_df_melted

zri_df_full <-zri_df_melted %>% 
  mutate(dates=ym(variable), Month_Yr = format_ISO8601(dates, precision = "ym")) %>%
  select(-variable) %>% rename(avg_rent = value) 

zri_df_full <- zri_df_full %>% tsibble(dates = yearmonth(dates), index = dates)



zri_df_full$ym <- yearmonth(zri_df_full$dates) %>%
  select(-dates)


# zri_df_full <-zri_df_melted %>% 
#   mutate(dates=ym(variable))  %>%
#   select(-variable) %>% rename(avg_rent = value)


zri_df_full %>% as_tsibble(key = c(zip)) 

```



```{r}
zri_CA <- zri_df_full %>%
  filter(State == "CA")
zri_CA %>%
  group_by(City) %>%  slice(1)

```

```{r}
zri_CA <- zri_CA %>% as_tsibble(key = c(zip)) %>% tsibble::fill_gaps()
zri_CA %>% as_tsibble() %>%
  ggplot2::autoplot(avg_rent)


# zri_CA %>% group_by(zip) %>% na_interpolation(x)

# ggplot(data = zri_CA, aes(x = date, y = avg_rent)) +
#  geom_line(aes(color = CountyName), size = 1)
```


```{r}
qplot(variable, value, data = zri_CA, geom = "line", group = CountyName) +
    facet_grid(variable ~ ., scale = "free_y") +
    theme_bw()

ggplotly()
```

```{r}

CA_plot <- zri_CA %>% filter(zip == "90006" | zip == "90007") %>% filter_index(~"2018-12")
CA_plot_full <- zri_CA %>% filter(zip == "90006" | zip == "90007")
fit <- CA_plot %>%
  model(
    ets = ETS(avg_rent ~ trend("A")),
    arima = ARIMA(avg_rent)
  )
fit
```


```{r}

CA_plot <- zri_CA %>% filter_index(~"2018-12")
# CA_plot_full <- zri_CA %>% filter(zip == "90006")
fit_CA <- CA_plot %>%
  model(
    ets = ETS(avg_rent ~ trend("Ad")),
    arima = ARIMA(avg_rent)
  )
fit

fit %>%
  glance()
```


```{r}
fc <- fit_CA %>% filter(zip == "90006") %>%
  forecast(h = "1 year")
fc
```

```{r}
CA_plot_full <- zri_CA %>% filter(zip == "90006")
fc %>%
  autoplot(CA_plot_full)
```

