---
title: "Testing_VA"
author: "Oren"
date: "9/18/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(fable)
library(tsibble)
library(dplyr)
library(tidyverse)
library(reshape2)
library(ggplot2)
library(plotly)
library(feasts)
library(imputeTS)
library(tidymodels)
library(skimr)
library(zoo)
library(lubridate)
library(lme4)
```



```{r}
zri_df_og <-read_csv("../../data/HIER_zri_multifamily_v2.csv")
taxes_df_og <-read_csv("../data/final_TAXES_by_zip.csv")
```



```{r}
zri_df <- select(zri_df_og, -c('SizeRank', 'Metro')) 

zri_df <- drop_na(zri_df)

zri_df_melted <- melt(zri_df, id.vars = c('zip', 'City', 'State',  'CountyName'))
zri_df_melted

zri_df_full <-zri_df_melted %>% 
  mutate(dates=ym(variable), Month_Yr = format_ISO8601(dates, precision = "ym")) %>%
  select(-variable) %>% rename(avg_rent = value) 

# zri_df_full <- zri_df_full %>% tsibble(dates = yearmonth(dates), index = dates)



zri_df_full$ym <- yearmonth(zri_df_full$dates) 



# zri_df_full <- zri_df_ful %>%
#   select(-dates)


# zri_df_full <-zri_df_melted %>% 
#   mutate(dates=ym(variable))  %>%
#   select(-variable) %>% rename(avg_rent = value)


zri_df_full <- zri_df_full %>% as_tsibble(key = c(zip), index = c(ym)) 

```
```{r}
taxes_df <- taxes_df_og

taxes_df$date <- stri_c(taxes_df$year,taxes_df$month, sep="-", collapse=NULL, ignore_null=TRUE)

taxes_df$ym <- yearmonth(taxes_df$date) 

taxes_df <- taxes_df %>% select(c(ZIPCODE, state_local_perc, ym))

taxes_df <- taxes_df %>% as_tsibble(key = c(ZIPCODE), index = c(ym)) 

```


```{r}
full_df <- inner_join(zri_df_full, taxes_df, by= c("zip" = "ZIPCODE", "ym" = "ym"))

```



```{r}

zri_VA <- full_df %>%
  filter(State == "VA")

zri_VA <- zri_VA %>% as_tsibble(key = c(zip)) %>% tsibble::fill_gaps()
zri_VA %>% as_tsibble() %>%
  ggplot2::autoplot(avg_rent)

```

```{r}
zri_VA <- full_df %>%
  filter(State == "VA")
VA_plot <- zri_VA %>% filter_index(~"2017-12")

fit_VA <- VA_plot %>%
  model(
    ets = ETS(avg_rent ~ state_local_perc + error("M") + trend(method = c("N", "A", "Ad")) + season(method = c("N", "A", "M"))),
    arima = ARIMA(avg_rent),
    
  )
fit_VA

fit_VA %>%
  glance()
```


```{r}
fc <- fit_VA %>% filter(zip == "22031") %>%
  forecast(h = "1 year")
fc
```

```{r}
zri_VA <- zri_VA %>% filter(zip == "22031")
fc %>% autoplot(zri_VA)
```


```{r}
zri_VA_leveled <- zri_VA %>%
  aggregate_key((State/CountyName/City/zip), sum_rent = sum(avg_rent))

fit <- zri_VA_leveled %>%
  filter_index(~"2018-12") %>%
  model(base = ETS(sum_rent)) %>%
  reconcile(
    bu = bottom_up(base),
    ols = min_trace(base, method = "ols"),
    mint = min_trace(base, method = "mint_shrink"),
)

```

```{r}
accuracy(fit)
```

```{r}
fc <- fit %>% forecast(h = "1 year")
fc

```

```{r}
fc %>%
  # filter(is_aggregated(State), is_aggregated(City)) %>%
  autoplot(
    zri_VA_leveled ,
    level = NULL
  ) +
  facet_wrap(vars(zip), scales = "free_y")



# zri_VA <- zri_VA %>% filter(zip == "22031")
autoplot(fc %>% filter(zip == "22031")) 

%>% autoplot(zri_VA)
```

